services:
  - type: web
    name: test-svc
    env: ruby
    autoDeploy: false
    domains:
      - test123.onrender.com
    buildCommand: bundle install
    startCommand: bundle exec ruby main.rb
    disk:
      name: data
      mountPath: /data
      sizeGB: 10
databases:
  - name: pg_my_cool_db
    databaseName: pg_my_cool_db
